name: Daily update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout script
        uses: actions/checkout@v2

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: dump
          path: data

      - name: Configure and start MySQL
        run: |
          echo 'secure_file_priv=""' | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo systemctl start mysql.service
          mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS dfki;'

      - name: Prepare database
        run: |
          sudo mkdir /tmp/datadir && sudo chmod 777 /tmp/datadir
          gzip -d data/rki_csv.sql.gz
          mysql --defaults-extra-file=.github/workflows/github-actions-sql.cnf dfki < data/rki_csv.sql
          rm data/rki_csv.sql

      - name: Run update
        run: |
          ./replay.sh --dir=/tmp/datadir --chmod .github/workflows/github-actions-sql.cnf > out.txt

      - name: Create dump and commit
        run: |
          mysqldump --defaults-extra-file=.github/workflows/github-actions-sql.cnf dfki | gzip -9 > data/rki_csv.sql.gz
          cd data
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add rki_csv.sql.gz
          cat ../out.txt >> RKI-Data-Diff.log
          git add RKI-Data-Diff.log
          sed -i 's/# //' ../out.txt
          git commit -F ../out.txt
          git push origin dump
