name: Test manual action run
on:
  workflow_dispatch:
    inputs:
      puppy:
        description: 'A kind of puppy.'
        required: true

jobs:
  activation:
    name: Print the input
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Print puppy type
        id: printPuppyType
        run: echo The puppy is ${{ github.event.inputs.puppy }}
